### ISSUE TITLE
Time passed between function calls not necessarily correct

### ISSUE THREAD

**Issue by RicardoHenriques** [Touratica/html-scoreboard#100]
timePassed shouldn't be calculated based on last function's execution, but based on initial time instead.

https://github.com/Touratica/html-scoreboard/blob/4f1176d634f76e46e05fd0d8619df480f956edb9/src/index.ts#L196

**Comment by Touratica** [comment]
The time that passed can't be calculated this way, as the timer can be paused and later resumed.
